trigger: none

pool: Default

stages:
  - stage: Validate
    jobs:
      - job: linter_validation
        steps:
          - script: |
              ansible-lint $(Build.SourcesDirectory)/servers.yml
